"""Repository interfaces (Protocols) for finance domain."""

from decimal import Decimal
from datetime import date
from typing import Protocol
from uuid import UUID

from app.modules.finance.domain.entities import (
    Account,
    AccountCategory,
    Transaction,
    BudgetMonth,
    BudgetAllocation,
)


class AccountCategoryRepository(Protocol):
    def create(self, category: AccountCategory) -> AccountCategory: ...
    def get_by_id(self, category_id: UUID, tenant_id: UUID) -> AccountCategory | None: ...
    def get_by_name(self, name: str, tenant_id: UUID) -> AccountCategory | None: ...
    def list(self, tenant_id: UUID, page: int, page_size: int) -> tuple[list[AccountCategory], int]: ...
    def update(self, category: AccountCategory) -> AccountCategory: ...


class AccountRepository(Protocol):
    def create(self, account: Account) -> Account: ...
    def get_by_id(self, account_id: UUID, tenant_id: UUID) -> Account | None: ...
    def get_by_name_and_type(self, name: str, type: str, tenant_id: UUID) -> Account | None: ...
    def list(self, tenant_id: UUID, page: int, page_size: int) -> tuple[list[Account], int]: ...
    def update(self, account: Account) -> Account: ...


class TransactionRepository(Protocol):
    def create(self, transaction: Transaction) -> Transaction: ...
    def get_by_id(self, transaction_id: UUID, tenant_id: UUID) -> Transaction | None: ...
    def list(
        self,
        tenant_id: UUID,
        page: int,
        page_size: int,
        account_id: UUID | None,
        direction: str | None,
        from_date: date | None,
        to_date: date | None,
    ) -> tuple[list[Transaction], int]: ...
    def update(self, transaction: Transaction) -> Transaction: ...
    def delete(self, transaction_id: UUID, tenant_id: UUID) -> None: ...


class BudgetMonthRepository(Protocol):
    """Repository interface for budget months."""
    def create(self, budget_month: BudgetMonth) -> BudgetMonth: ...
    def get_by_month(self, tenant_id: UUID, month: date) -> BudgetMonth | None: ...
    def get_by_id(self, budget_month_id: UUID, tenant_id: UUID) -> BudgetMonth | None: ...
    def update(self, budget_month: BudgetMonth) -> BudgetMonth: ...


class BudgetAllocationRepository(Protocol):
    """Repository interface for budget allocations."""
    def create(self, allocation: BudgetAllocation) -> BudgetAllocation: ...
    def get_by_budget_and_category(self, budget_month_id: UUID, category_id: UUID) -> BudgetAllocation | None: ...
    def list_by_budget(self, budget_month_id: UUID) -> list[BudgetAllocation]: ...
    def bulk_update(self, allocations: list[BudgetAllocation]) -> list[BudgetAllocation]: ...
